name: smartly
description: A new Flutter project.
publish_to: "none"
version: 1.0.1+2

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  loading_animation_widget: ^1.2.0+4
  http: ^0.13.5
  share_plus: ^6.3.1
  flutter_linkify: ^5.0.2
  shared_preferences: ^2.0.17
  url_launcher: ^6.1.9
  persistent_bottom_nav_bar: ^5.0.2
  flutter_highlight: ^0.7.0
  extended_image: ^7.0.2
  path_provider: ^2.0.12
  image_gallery_saver: ^1.7.1
  dio: ^5.0.0
  firebase_analytics: ^10.1.3
  firebase_core: ^2.6.1
  firebase_messaging: ^14.2.4
  cupertino_icons: ^1.0.5
  google_mobile_ads: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
